### Get all owners
GET http://localhost:9080/cat-app/api/owners

### Get actual owner
GET http://localhost:9080/cat-app/api/owners/d80ecfee-a46f-4d05-b02c-8e9664b5982f

### Get non existing owner
GET http://localhost:9080/cat-app/api/owners/7ab007bf-7a04-4223-b5b0-760db8fff539

### create new owner
PUT http://localhost:9080/cat-app/api/owners/c66de235-cb3d-4880-8c18-43e86d0fac75
Content-Type: application/json

{
  "name": "matidon",
  "login": "turbomati",
  "birthDate": "1990-01-01",
  "salary": "105000.0",
  "password": "Shhhh!!!Quiet"
}


### Delete owner
DELETE http://localhost:9080/cat-app/api/owners/c66de235-cb3d-4880-8c18-43e86d0fac75


### get image
GET http://localhost:9080/cat-app/api/images/d80ecfee-a46f-4d05-b02c-8e9664b5982f

### delete iamge
DELETE http://localhost:9080/cat-app/api/images/d80ecfee-a46f-4d05-b02c-8e9664b5982f
###

### put image
PUT http://localhost:9080/cat-app/api/images/d80ecfee-a46f-4d05-b02c-8e9664b5982f
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/png

< ./45a3c22d-77d0-4571-9f4b-4de78b3e5796.png
--boundary--
###
